services:
  - type: web
    name: ghost-blog
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: https://blog-xf68.onrender.com
      - key: database__client
        value: sqlite3
      - key: database__connection__filename
        value: /var/lib/ghost/content/data/ghost.db
      # ⬇️ Cloudinary (이 4개가 핵심)
      - key: storage__active
        value: cloudinary
      - key: storage__cloudinary__cloud_name
        value: detbolvwl
      - key: storage__cloudinary__api_key
        value: 348292815391766
      - key: storage__cloudinary__api_secret
        value: d-s7oZgOqoz2J6nBFsuEY4igupc
