services:
  - type: web
    name: ghost-blog
    env: docker
    plan: free
    region: singapore

    # 영구 디스크 (게시글/이미지/테마 보존)
    disk:
      name: ghost-content
      mountPath: /var/lib/ghost/content
      sizeGB: 1

    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: https://placeholder.onrender.com
