services:
  - type: web
    name: ghost-blog
    env: docker
    plan: free
    region: singapore
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: url
        value: https://placeholder.onrender.com
      # DB를 Postgres로 외부화 (예시는 DATABASE_URL 한 줄 방식)
      - key: database__client
        value: postgres
      - key: database__connection__connectionString
        value: ${DATABASE_URL}
